services:

  bookmarker-db:
    image: postgres
    environment:
      - POSTGRES_USER=ghirmai
      - POSTGRES_PASSWORD=Learning@Good
      - POSTGRES_DB=MYDB2

    ports:
      - 15432:5432
    volumes:
      - /Users/Ghirmai/postgres_datapart:/var/lib/postgresql/data
    restart: always

